### ISSUE TITLE
yarn安装依赖，无法启动项目

### ISSUE THREAD

**Issue by daqi** [cmux/koot#99]
npm run dev:spa，报错
```
> xxxxxxxxxxxxxx@0.1.0 dev:spa /work/ux-xxxxxxxxxxxxxx-web2
> koot-dev --type spa

env: node\r: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! xxxxxxxxxxxxxx@0.1.0 dev:spa: `koot-dev --type spa`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the xxxxxxxxxxxxxx@0.1.0 dev:spa script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/qiyunjiang/.npm/_logs/2019-04-16T03_10_04_664Z-debug.log
```
log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/11.13.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev:spa' ]
2 info using npm@6.7.0
3 info using node@v11.13.0
4 verbose run-script [ 'predev:spa', 'dev:spa', 'postdev:spa' ]
5 info lifecycle xxxxxxxxxxxxxx@0.1.0~predev:spa: xxxxxxxxxxxxxx@0.1.0
6 info lifecycle xxxxxxxxxxxxxx@0.1.0~dev:spa: xxxxxxxxxxxxxx@0.1.0
7 verbose lifecycle xxxxxxxxxxxxxx@0.1.0~dev:spa: unsafe-perm in lifecycle true
8 verbose lifecycle xxxxxxxxxxxxxx@0.1.0~dev:spa: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/work/ux-xxxxxxxxxxxxxx-web2/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle xxxxxxxxxxxxxx@0.1.0~dev:spa: CWD: /work/ux-xxxxxxxxxxxxxx-web2
10 silly lifecycle xxxxxxxxxxxxxx@0.1.0~dev:spa: Args: [ '-c', 'koot-dev --type spa' ]
11 info lifecycle xxxxxxxxxxxxxx@0.1.0~dev:spa: Failed to exec dev:spa script
12 verbose stack Error: xxxxxxxxxxxxxx@0.1.0 dev:spa: `koot-dev --type spa`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:193:13)
12 verbose stack     at maybeClose (internal/child_process.js:1001:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
13 verbose pkgid xxxxxxxxxxxxxx@0.1.0
14 verbose cwd /work/ux-xxxxxxxxxxxxxx-web2
15 verbose Darwin 18.0.0
16 verbose argv "/usr/local/Cellar/node/11.13.0/bin/node" "/usr/local/bin/npm" "run" "dev:spa"
17 verbose node v11.13.0
18 verbose npm  v6.7.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error xxxxxxxxxxxxxx@0.1.0 dev:spa: `koot-dev --type spa`
23 error spawn ENOENT
24 error Failed at the xxxxxxxxxxxxxx@0.1.0 dev:spa script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by daqi** [comment]
https://github.com/yarnpkg/yarn/issues/5480
https://github.com/npm/npm/issues/12371#issuecomment-293211866

**Comment by Diablohu** [comment]
解决方案：在 publish 前，检查所有子包的 `package.json` 中 `bin` 项，将指向的所有文件的换行符转为 `LF`，并进行一次 `git commit`
